version: "3"
volumes:
  pg_data:
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - 3000:3000
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: trento
      RABBITMQ_DEFAULT_PASS: trento
  node01:
    profiles: ['agents']
    image: ghcr.io/trento-project/barbecue-hana_node01:latest
    hostname: hana_node01
    network_mode: host
    command:
      - --api-key
      - some-random-string
      - --facts-service-url
      - amqp://wanda:wanda@localhost:5674
      - --server-url
      - http://localhost:4000
  node02:
    profiles: ['agents']
    image: ghcr.io/trento-project/barbecue-hana_node02:latest
    hostname: hana_node02
    network_mode: host
    command:
      - --api-key
      - some-random-string 
      - --facts-service-url
      - amqp://wanda:wanda@localhost:5674
      - --server-url
      - http://localhost:4000
